/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Modelo.Comprador;
import Persistencia.CompradorData;
import Persistencia.PeliculaData;
import java.time.LocalDate;
import java.time.ZoneId;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class compradorVista extends javax.swing.JInternalFrame {
private  SistemaCine sc;
private CompradorData cd;

    /**
     * Creates new form compradorVista
     */
    public compradorVista() {
        initComponents();
        sc=new SistemaCine();
        cd=new CompradorData(sc.conexionDb());
        txtid.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jbnuevo = new javax.swing.JButton();
        jbguardar = new javax.swing.JButton();
        jbmodificar = new javax.swing.JButton();
        jbbuscar = new javax.swing.JButton();
        jbeliminar = new javax.swing.JButton();
        txtfecha = new com.toedter.calendar.JDateChooser();
        txtid = new javax.swing.JTextField();
        txtdni = new javax.swing.JTextField();
        txtnombre = new javax.swing.JTextField();
        txtpassword = new javax.swing.JTextField();
        jbsalir = new javax.swing.JButton();
        txtmediopago = new javax.swing.JComboBox<>();

        jLabel1.setFont(new java.awt.Font("Sylfaen", 2, 18)); // NOI18N
        jLabel1.setText("Comprador");

        jLabel2.setText("ID");

        jLabel3.setText("DNI");

        jLabel4.setText("Nombre");

        jLabel5.setText("Password");

        jLabel6.setText("medio Pago");

        jLabel7.setText("Fecha de nacimiento");

        jbnuevo.setText("nuevo");
        jbnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnuevoActionPerformed(evt);
            }
        });

        jbguardar.setText("guardar");
        jbguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbguardarActionPerformed(evt);
            }
        });

        jbmodificar.setText("modificar");
        jbmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbmodificarActionPerformed(evt);
            }
        });

        jbbuscar.setText("buscar");
        jbbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbbuscarActionPerformed(evt);
            }
        });

        jbeliminar.setText("eliminar");
        jbeliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbeliminarActionPerformed(evt);
            }
        });

        jbsalir.setText("salir");
        jbsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbsalirActionPerformed(evt);
            }
        });

        txtmediopago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Efectivo", "Debito", "Credito", "Transferencia" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(37, 37, 37)
                                .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(txtmediopago, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jbnuevo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbguardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbmodificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbeliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbsalir))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jLabel3)
                                .addGap(23, 23, 23))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(txtdni, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(58, 58, 58)
                        .addComponent(jbbuscar)))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtdni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbbuscar)))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtmediopago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbnuevo)
                            .addComponent(jbguardar)
                            .addComponent(jbmodificar)
                            .addComponent(jbeliminar)
                            .addComponent(jbsalir)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtfecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbguardarActionPerformed
      
       txtid.setText("");
        Comprador c;
      
      if(txtdni.getText().isEmpty()||txtpassword.getText().isEmpty()||txtmediopago.getSelectedIndex()== -1||txtnombre.getText().isEmpty()){
       JOptionPane.showMessageDialog(null, "todos los campos son obligatorios");
       return;
       }
      try{
        int dni=Integer.parseInt(txtdni.getText());  
        String contra=(txtpassword.getText());
        String pago=txtmediopago.getSelectedItem().toString();
        String nombre=txtnombre.getText();
        
        if(txtfecha.getDate()==null){
        JOptionPane.showMessageDialog(null, "debe seleccionar una fecha");
        return;
        }
       LocalDate fecha=txtfecha.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
       
       c= new Comprador(dni,nombre,contra,pago,fecha);
       cd.guardarComprador(c);
          JOptionPane.showMessageDialog(this, "Comprador guardado correctamente.");
       }catch(NumberFormatException e){JOptionPane.showMessageDialog(null, "dni deben ser numericos");
       
     }
      
     limpiar();
    }//GEN-LAST:event_jbguardarActionPerformed

    private void jbmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbmodificarActionPerformed
     if(txtid.getText().isEmpty()){
        JOptionPane.showMessageDialog(null, "Debe buscar un comprador antes de modificar.");
        return;
    }

    if(txtdni.getText().isEmpty() ||
       txtnombre.getText().isEmpty() ||
       txtpassword.getText().isEmpty() ||
       txtmediopago.getSelectedIndex() == -1){
        
        JOptionPane.showMessageDialog(null, "Todos los campos son obligatorios.");
        return;
    }

    if(txtfecha.getDate() == null){
        JOptionPane.showMessageDialog(null, "Debe ingresar una fecha.");
        return;
    }

    try {
        int id = Integer.parseInt(txtid.getText());
        int dni = Integer.parseInt(txtdni.getText());
        String nombre = txtnombre.getText();
        String contra = txtpassword.getText();
        String pago = txtmediopago.getSelectedItem().toString();  
        LocalDate fecha = txtfecha.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();

     
        Comprador c = new Comprador(dni, nombre, contra, pago, fecha);
        c.setIdComprador(id);

        cd.modificarComprador(c);

        JOptionPane.showMessageDialog(null, "Modificado exitosamente.");
        limpiar();

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "DNI e ID deben ser numéricos.");
    }
    }//GEN-LAST:event_jbmodificarActionPerformed

    private void jbeliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbeliminarActionPerformed
      txtid.setEditable(true);
          if(txtid.getText().isEmpty()){
              JOptionPane.showMessageDialog(null, "ingrese el id del comprador que desea eliminar");
              return;
          }
          
        int id = Integer.parseInt(txtid.getText());
        
        
        try{
            cd.eliminarComprador(id);
        }catch(Exception e){JOptionPane.showMessageDialog(null, "Eliminado exitosamente"); }
         
            limpiar(); 
      
   
     
    }//GEN-LAST:event_jbeliminarActionPerformed

    private void jbnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnuevoActionPerformed
     
        
        limpiar();
       txtid.setText("");
        txtid.setEditable(false);
    }//GEN-LAST:event_jbnuevoActionPerformed

    private void jbbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbbuscarActionPerformed
     String dniTexto = txtdni.getText();
       
       if(dniTexto.isEmpty()){
       JOptionPane.showMessageDialog(this, "Ingrese un DNI para buscar.");
       return;
       }
       try{
           int dni = Integer.parseInt(dniTexto);
           Comprador c = cd.buscarPorDni(dni);
           
           if(c != null){
               txtid.setText(c.getIdComprador() + "");
               txtnombre.setText(c.getNombre());
               txtpassword.setText(c.getPassword());
               txtmediopago.setSelectedItem(c.getMedioPago());
               txtfecha.setDate(java.sql.Date.valueOf(c.getFechaNac()));
           }else{
               JOptionPane.showMessageDialog(this, "No existe comprador con ese Dni");
           }
       }catch(NumberFormatException e){
           JOptionPane.showMessageDialog(this, "El DNI debe ser numerico");
       }   
         
    }//GEN-LAST:event_jbbuscarActionPerformed

    private void jbsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbsalirActionPerformed
        dispose();
    }//GEN-LAST:event_jbsalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton jbbuscar;
    private javax.swing.JButton jbeliminar;
    private javax.swing.JButton jbguardar;
    private javax.swing.JButton jbmodificar;
    private javax.swing.JButton jbnuevo;
    private javax.swing.JButton jbsalir;
    private javax.swing.JTextField txtdni;
    private com.toedter.calendar.JDateChooser txtfecha;
    private javax.swing.JTextField txtid;
    private javax.swing.JComboBox<String> txtmediopago;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtpassword;
    // End of variables declaration//GEN-END:variables
private void limpiar() {
    
        txtid.setText("");
        txtdni.setText("");
        txtnombre.setText("");
        txtpassword.setText("");
        txtmediopago.setSelectedIndex(-1);
        txtfecha.setDate(null);
        
}  
}
