/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Modelo.Comprador;
import Modelo.Sala;
import Persistencia.SalaData;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class salaVista extends javax.swing.JInternalFrame {
private  SistemaCine sc= new SistemaCine();

private SalaData sd= new SalaData(sc.conexionDb());

    /**
     * Creates new form salaVista
     */
    public salaVista() {
        initComponents();
        txtid.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jbnuevo = new javax.swing.JButton();
        jbguardar = new javax.swing.JButton();
        jbmodificar = new javax.swing.JButton();
        jbeliminar = new javax.swing.JButton();
        jbbuscar = new javax.swing.JButton();
        txtapta3d = new javax.swing.JCheckBox();
        txtestado = new javax.swing.JCheckBox();
        txtid = new javax.swing.JTextField();
        txtnrosala = new javax.swing.JTextField();
        txtcapacidad = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        jLabel1.setText("sala");

        jLabel2.setText("ID");

        jLabel3.setText("nroSala");

        jLabel4.setText("apta3D");

        jLabel5.setText("capacidad");

        jLabel6.setText("activa");

        jbnuevo.setText("nuevo");
        jbnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnuevoActionPerformed(evt);
            }
        });

        jbguardar.setText("guardar");
        jbguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbguardarActionPerformed(evt);
            }
        });

        jbmodificar.setText("modificar");
        jbmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbmodificarActionPerformed(evt);
            }
        });

        jbeliminar.setText("dar baja");
        jbeliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbeliminarActionPerformed(evt);
            }
        });

        jbbuscar.setText("buscar");
        jbbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbbuscarActionPerformed(evt);
            }
        });

        txtestado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtestadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtestado, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtcapacidad, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                            .addComponent(txtnrosala)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(txtapta3d))
                            .addComponent(txtid))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbbuscar)
                        .addGap(50, 50, 50))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jbnuevo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbguardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbmodificar)
                        .addGap(18, 18, 18)
                        .addComponent(jbeliminar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbbuscar)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtnrosala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtapta3d)
                    .addComponent(jLabel4))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtcapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtestado)
                    .addComponent(jLabel6))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbguardar)
                    .addComponent(jbmodificar)
                    .addComponent(jbnuevo)
                    .addComponent(jbeliminar))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnuevoActionPerformed
       limpiar();
       txtid.setText("");
        txtid.setEditable(false);
    }//GEN-LAST:event_jbnuevoActionPerformed

    private void jbguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbguardarActionPerformed
      Sala s;
      
      if(txtnrosala.getText().isEmpty()||txtcapacidad.getText().isEmpty()){
      JOptionPane.showMessageDialog(null, "campos vacios!");
      return;
      };
      try{
      int nrosala=Integer.parseInt(txtnrosala.getText());
      boolean apta3d=txtapta3d.isSelected();
      int capacidad=Integer.parseInt(txtcapacidad.getText());
      boolean estado=txtestado.isSelected();
      
      
      
      s=new Sala(nrosala,apta3d,capacidad,estado);
      sd.guardarSala(s);
      JOptionPane.showMessageDialog(null, "Sala guardada ");
      }catch(NumberFormatException e){
       JOptionPane.showMessageDialog(null, "deben ingresar valores numericos");
      
      }
      limpiar();
      txtid.setText("");
    }//GEN-LAST:event_jbguardarActionPerformed

    private void txtestadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtestadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtestadoActionPerformed

    private void jbbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbbuscarActionPerformed
      
        
        if(txtnrosala.getText().isEmpty()){
        
      JOptionPane.showMessageDialog(null, "ingrese el numero de la sala que desea buscar");
        return;
        }
      Sala s= sd.buscarSala(Integer.parseInt(txtnrosala.getText()));
        txtid.setText(s.getIdSala()+"");
        txtnrosala.setText(s.getNroSala()+"");
        txtapta3d.setSelected(s.isApta3D());
        txtcapacidad.setText(s.getCapacidad()+"");
        txtestado.setSelected(s.getEstado());
       
        
    }//GEN-LAST:event_jbbuscarActionPerformed

    private void jbmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbmodificarActionPerformed
    
        Sala s;
       if(txtnrosala.getText().isEmpty()||txtcapacidad.getText().isEmpty()){
      JOptionPane.showMessageDialog(null, "campos vacios!");
      return;
      };
        
      try{  
        int nrosala=Integer.parseInt(txtnrosala.getText());
         boolean apta3d=txtapta3d.isSelected();
         int capacidad=Integer.parseInt(txtcapacidad.getText());
          boolean estado= txtestado.isSelected();
          s=new Sala(nrosala,apta3d,capacidad,estado);
           s.setIdSala(Integer.parseInt(txtid.getText()));
          sd.modificarSala(s);
      }catch(NumberFormatException e){
       JOptionPane.showMessageDialog(null, "deben ingresar valores numericos");
      
      }
          limpiar();
          txtid.setText("");
          
    }//GEN-LAST:event_jbmodificarActionPerformed

    private void jbeliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbeliminarActionPerformed
txtid.setEditable(true);
        if(txtid.getText().isEmpty()){
        
        JOptionPane.showMessageDialog(null, "ingrese el id de la sala que  desea dar de baja");
        return;
        }
        try{
        int id=Integer.parseInt(txtid.getText());
       
       sd.bajaLogicaSala(id);
       
        }catch(NumberFormatException e){
        
          JOptionPane.showMessageDialog(null, "ingrese un valor numerico");
        }
       txtid.setText("");
        txtid.setEditable(false);
       limpiar();
      
    }//GEN-LAST:event_jbeliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton jbbuscar;
    private javax.swing.JButton jbeliminar;
    private javax.swing.JButton jbguardar;
    private javax.swing.JButton jbmodificar;
    private javax.swing.JButton jbnuevo;
    private javax.swing.JCheckBox txtapta3d;
    private javax.swing.JTextField txtcapacidad;
    private javax.swing.JCheckBox txtestado;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtnrosala;
    // End of variables declaration//GEN-END:variables
private void limpiar() {
        
       txtid.setText("");
        txtnrosala.setText("");
        txtapta3d.setSelected(false);
        txtcapacidad.setText("");
       txtestado.setSelected(false);
        
       
        

    }
}
