/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Modelo.Comprador;
import Modelo.Conexion;
import Modelo.Lugar;
import Modelo.Proyeccion;
import Modelo.Ticket;
import Persistencia.CompradorData;
import Persistencia.LugarData;
import Persistencia.ProyeccionData;
import Persistencia.TicketData;
import java.sql.Connection;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class ticketVista extends javax.swing.JInternalFrame {
SistemaCine sc=new SistemaCine();
 CompradorData cd;
  ProyeccionData pd;
 LugarData ld;
 TicketData td;
 
    /**
     * Creates new form ticketVista
     */
    public ticketVista() {
        initComponents();
         Conexion conexion = sc.conexionDb();
        cd= new CompradorData(conexion);
       ld= new LugarData(conexion);
       pd= new ProyeccionData(conexion);
       td=new TicketData(conexion);
       txtid.setEditable(false);
        llenarCombo();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCalendar1 = new com.toedter.calendar.JCalendar();
        textField3 = new java.awt.TextField();
        jLabel1 = new javax.swing.JLabel();
        txtcomprador = new javax.swing.JComboBox<>();
        txtProyeccion = new javax.swing.JComboBox<>();
        txtlugar = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtfechafuncion = new com.toedter.calendar.JDateChooser();
        txtfechacompra = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtid = new java.awt.TextField();
        jLabel7 = new javax.swing.JLabel();
        txtmonto = new java.awt.TextField();
        txtactivo = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        jbanular = new javax.swing.JButton();
        jbguardar = new javax.swing.JButton();
        jbbuscar = new javax.swing.JButton();
        jbsalir = new javax.swing.JButton();

        textField3.setText("textField3");

        jLabel1.setText("Ticket");

        txtcomprador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcompradorActionPerformed(evt);
            }
        });

        txtProyeccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProyeccionActionPerformed(evt);
            }
        });

        txtlugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlugarActionPerformed(evt);
            }
        });

        jLabel2.setText("comprador");

        jLabel3.setText("Proyeccion");

        jLabel4.setText("Asientos de la proyeccion seleccionada:");

        jLabel5.setText("fecha de compra");

        jLabel6.setText("fecha de funcion");

        txtid.setEnabled(false);
        txtid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidActionPerformed(evt);
            }
        });

        jLabel7.setText("id");

        txtmonto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmontoActionPerformed(evt);
            }
        });

        txtactivo.setText("activo");
        txtactivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtactivoActionPerformed(evt);
            }
        });

        jLabel8.setText("monto");

        jbanular.setText("anular ticket");
        jbanular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbanularActionPerformed(evt);
            }
        });

        jbguardar.setText("guardar");
        jbguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbguardarActionPerformed(evt);
            }
        });

        jbbuscar.setText("buscar");
        jbbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbbuscarActionPerformed(evt);
            }
        });

        jbsalir.setText("salir");
        jbsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbsalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtmonto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel5)
                            .addComponent(jbguardar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtfechacompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtfechafuncion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbanular)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbbuscar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbsalir))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtlugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(jLabel1))
                            .addComponent(txtProyeccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txtactivo)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtcomprador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel7))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtcomprador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtProyeccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtlugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtfechacompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5))
                    .addComponent(txtfechafuncion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtmonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtactivo)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbguardar)
                    .addComponent(jbanular)
                    .addComponent(jbbuscar)
                    .addComponent(jbsalir))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtProyeccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProyeccionActionPerformed
         Proyeccion seleccionada = (Proyeccion) txtProyeccion.getSelectedItem();
        if (seleccionada != null) {
          
            cargarlugares(seleccionada.getIdProyeccion());
        }
    
    }//GEN-LAST:event_txtProyeccionActionPerformed

    private void txtlugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlugarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlugarActionPerformed

    private void txtmontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmontoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmontoActionPerformed

    private void txtactivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtactivoActionPerformed
        // TODO add your handling code here:
         
       
    }//GEN-LAST:event_txtactivoActionPerformed

    private void jbguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbguardarActionPerformed
        Ticket t;
        if (txtfechacompra.getDate() == null || txtfechafuncion.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar ambas fechas ");
            return;
        }
        if (txtmonto.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe ingresar el monto del ticket.");
            return;
        }
      

        try{
        Comprador c=(Comprador) txtcomprador.getSelectedItem();
        Lugar l=(Lugar) txtlugar.getSelectedItem();
        int id=Integer.parseInt(txtid.getText());
        LocalDate fechac=txtfechacompra.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        LocalDate fechaf=txtfechafuncion.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        Double monto=Double.parseDouble(txtmonto.getText());
        boolean activo=txtactivo.isSelected();
        t=new Ticket(id,l,c,fechac,fechaf,monto,activo);
        
        td.guardarTicket(t);
        
        }catch(NumberFormatException r){
        JOptionPane.showMessageDialog(null, "debe ingresar un valor numerico");
        
        }
        
    }//GEN-LAST:event_jbguardarActionPerformed

    private void jbbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbbuscarActionPerformed
txtid.setEnabled(true);
        if(txtid.getText().isEmpty()){
        
      JOptionPane.showMessageDialog(null, "ingrese el id del ticket que desea buscar");
        return;
        }
        try{
        
        int id=Integer.parseInt(txtid.getText());
        
        
       Ticket t= td.buscarTicket(id);
       
       txtmonto.setText(String.valueOf(t.getMonto()));
            LocalDate pe= t.getFechaFuncion();
        
              java.util.Date date = java.util.Date.from(pe.atStartOfDay(ZoneId.systemDefault()).toInstant());
     txtfechafuncion.setDate(date);
     
     LocalDate po= t.getFechaCompra();
        
              java.util.Date dat = java.util.Date.from(po.atStartOfDay(ZoneId.systemDefault()).toInstant());
     txtfechacompra.setDate(dat);
  
            txtcomprador.setSelectedItem(t.getComprador());
            txtlugar.setSelectedItem(t.getAsiento());
           txtactivo.setSelected(t.isActivo());
          
       }catch(NumberFormatException e){
        JOptionPane.showMessageDialog(null, "debe ingresar un valor numerico");
        }
    }//GEN-LAST:event_jbbuscarActionPerformed

    private void jbanularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbanularActionPerformed
      txtid.setEnabled(true);
        if(txtid.getText().isEmpty()){
       JOptionPane.showMessageDialog(null, "debe ingresar el id del ticket que desea anular");
      return;
      }
      try{  
        int id=Integer.parseInt(txtid.getText());
        td.anularTicket(id);
        limpiarcampo();
        txtid.setEnabled(false);
      }catch(NumberFormatException e){
      JOptionPane.showMessageDialog(null, "debe ingresar un valor numerico");
      
      }
    }//GEN-LAST:event_jbanularActionPerformed

    private void txtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidActionPerformed

    private void jbsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbsalirActionPerformed
dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jbsalirActionPerformed

    private void txtcompradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcompradorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcompradorActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton jbanular;
    private javax.swing.JButton jbbuscar;
    private javax.swing.JButton jbguardar;
    private javax.swing.JButton jbsalir;
    private java.awt.TextField textField3;
    private javax.swing.JComboBox<Proyeccion> txtProyeccion;
    private javax.swing.JCheckBox txtactivo;
    private javax.swing.JComboBox<Comprador> txtcomprador;
    private com.toedter.calendar.JDateChooser txtfechacompra;
    private com.toedter.calendar.JDateChooser txtfechafuncion;
    private java.awt.TextField txtid;
    private javax.swing.JComboBox<Lugar> txtlugar;
    private java.awt.TextField txtmonto;
    // End of variables declaration//GEN-END:variables

public void llenarCombo(){
List<Comprador>compradores= cd.listarCompradores();
for(Comprador c:compradores){
txtcomprador.addItem(c);

}
List<Proyeccion> proyecciones= pd.listarProyeccion();
for(Proyeccion pro:proyecciones){
    txtProyeccion.addItem(pro);
}
}
public void cargarlugares(int id){
   
    txtlugar.removeAllItems();
List<Lugar>lugares=ld.lugaresDisponiblesPorProyeccion(id);
for(Lugar l:lugares){
txtlugar.addItem(l);

}


}
public void limpiarcampo(){



   
    txtid.setText("");
    txtmonto.setText("");

     txtfechacompra.setDate(null);
    txtfechafuncion.setDate(null);
 txtcomprador.setSelectedIndex(-1); 
   
    txtProyeccion.setSelectedIndex(-1); 
    
    txtlugar.removeAllItems(); 
txtactivo.setSelected(false);
    
   




}
}
